# Generated by Django 3.1.3 on 2020-12-12 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0002_auto_20201211_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srkinvoicepayment',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 4, 54, 45, 481456, tzinfo=utc)),
        ),
    ]
