# Generated by Django 3.1.3 on 2020-12-12 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0005_auto_20201212_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srkinvoicepayment',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 18, 27, 20, 236470, tzinfo=utc)),
        ),
    ]
