# Generated by Django 3.1.3 on 2020-12-12 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0006_auto_20201212_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srkcustomers',
            name='cust_email',
        ),
        migrations.AlterField(
            model_name='srkinvoicepayment',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 22, 54, 56, 706845, tzinfo=utc)),
        ),
    ]
